name: upload-file-to-firebase-storage
description: Upload file to firebase storage
author: Tech Innovation SAC

inputs:
  file:
    description: 'File to upload'
    required: true
  destination:
    description: 'Destination path'
    required: true
  service_account_cert: 
    description: 'Service account cert'
    required: true
  storage_bucket:
    description: 'Storage bucket'
    required: true
  get_download_url: 
    description: 'Get download url'
    required: false
    default: false

outputs:
  url:
    description: 'Firebase Storage file url'

runs:
  using: node18
  main: index.js